---
title: Designing a High School Programming Class
author: Amrit Patel
date: '2019-04-02'
categories:
  - R
  - teaching
tags:
  - R Markdown
slug: designing-a-high-school-programming-class
draft: true
---

Goals: 

- Make and host an open source website.

- Final Project: Create a website post incorporating what you've learned.

3. Make an R Presentation incorporating 10 R Markdown features.
3a. What makes a good presentation?
3b. Output to various formats (i.e., HTML, PDF, Word). Practice Exercise: Write an assignment for another class in R Markdown and submit it.
4. Using R Markdown, make a blog post on any subject.
5. Introduce libraries.
6. Learn `blogdown`.
7. Setup the default blogdown website.
8. Add a page to your site.
8a. Assignment to choose a website 
 theme (for fun).
9. Learn to add basic elements (e.g., images, GIFs, hyperlinks, embedded video).
10. Introduce git (basics only to allow for website hosting).
11. Discuss open source.
12. Learn GitHub
12a. Build ggplot2 book @ https://github.com/hadley/ggplot2-book
13. Host website on GitHub.
14. Learn R basics (use Swirl?).
14a. Check out https://rstudio.cloud/?
15. Learn dplyr (basics enough for ggplot).
16. Learn ggplot (maybe show cool things like library(animation) or library(manipulate)).
16a. What makes a good plot?
17. Solve some data analysis problem.

### Week 1 - Introduction

1. Class intro + syllabus review; demo via presentation on GitHub hosted website.
2. Get to know students (skill level and interests). What is programming? Why learn it? [Review top languages](https://spectrum.ieee.org/static/interactive-the-top-programming-languages-2018). What do you want your website to be about?
3. Download RStudio.[^1] 
4. Demo features; show how to make a presentation; go over [rules of markdown](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf). Assignment: Each student make a slide on norms.
5. Work on norm slides. Assemble slides. I will host on my GitHub. Future assignment to have students request changes.

[^1]: Checkout https://rstudio.cloud/?

Week 2 - R Markdown

1. Learn about R chunks.
2. Write an essay.

Week 3

Week 4

Week 5

Week 6

Week 7

Week 8

Week 9

Week 10

Week 11

Week 12

Week 13

Week 14

Week 15

Week 16

Week 17

Week 18
