---
title: Is that it?
author: Amrit Patel
date: '2020-03-30'
slug: is-that-it
categories:
  - running
tags:
  - regression
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.align = "center")
```

Just like that, the [100 lap challenge](https://amritpatel.rbind.io/2020/03/27/100-lap-challenge/) is over. On my next try, I completed 100 sweltering laps. What surprised me was how tired I was at the outset from not getting enough sleep the night before. I guess it really shows what you can do if you put your mind toward something.

```{r, message = F}
source("~/GitHub/myBlog/content/resources/2020-03-27-100-lap-challenge/100LapChallengePrepare.R")
```

```{r, warning = F}
day4 <- getData("~/Downloads/Vadhana Running - 2020-03-30.csv") %>% mutate(Date = "2020-03-30")

day4 <- 
  day4 %>%
  mutate(Avg.Pace = Time.Sec / 60 / Distance) %>%
  select(-Time.Min) %>% rename(Time = Time.Sec)

# day4 %>% select(Date, everything())
```

```{r, message = F}
source("~/GitHub/myBlog/content/resources/2020-03-27-100-lap-challenge/100LapChallengeCombine.R")

```

```{r, message = F}
source("~/GitHub/myBlog/content/resources/2020-03-27-100-lap-challenge/100LapChallengeForPlot.R")
```

I noticed that something's up with Lap 50 as the RPI is unusually high.

```{r}
lessPlt %>%
  group_by(Date, variable) %>%
  filter(Date == "2020-03-30", variable == "RPI") %>%
  arrange(desc(value)) %>% top_n(5, value)

lessPlt %>%
  group_by(Date, variable) %>% 
  filter(Date =="2020-03-30", variable == "Avg.Pace") %>%
  arrange(value) %>%
  slice(1:5)
```

Let's remove it so as not to bias the average.

```{r}
lessPlt <- lessPlt %>% filter(variable != "RPI" | Date != "2020-03-30" | Laps != "50")

meanData <- pltRunData %>%
  # Mean data
  group_by(Date, variable) %>%
  filter(variable != "RPI" | Date != "2020-03-30" | Laps != "50") %>%
  summarise(avg = mean(value)) %>%
  # Add a column for mean value
  # plot position (y-coordinate)
  left_join(pltRunData %>% group_by(variable) %>%
              summarise(ypos = 0.95*max(value))) %>%
  filter(variable != "Distance")

lessMean <- meanData %>% filter(variable == "Avg.HR" |
                                  variable == "Avg.Pace" |
                                  variable == "Cadence" |
                                  variable == "Temp" |
                                  variable == "RPI"
                                  )
```

```{r}
ggplot(lessPlt, aes(x=Laps, y=value)) +
  geom_hline(data=lessMean, aes(yintercept = avg), colour="red", lty=3) +
  geom_text(data=lessMean,
            aes(label=round(avg,1), x=62, y=ypos),
            colour="red",
            hjust=1,
            size=3) +
  #xlim(c(1,65)) +
  geom_line() + 
  facet_grid(variable ~ Date, scales = "free")
```